### ISSUE TITLE
Get-VenafiCertificate else function needs VenafiSession

### ISSUE THREAD

**Issue by wilddev65** [gdbarron/VenafiPS#10]
# Environment

```
Operating System: Windows 10
VenafiPS version: 3.0.2
PowerShell version: 5.1
```

# Steps to reproduce

$sess = New-VenafiSession -Server $TPPServer -AccessToken $token.AccessToken -PassThru
Get-VenafiCertificate -VenafiSession $sess

# Expected behavior

Returns list of all certificates in system as 'Get-VenafiCertificate' would run in it's else statement;

Find-TppCertificate -Path '\ved' -Recursive -VenafiSession $VenafiSession

# Actual behavior

You must first connect to the TPP server with New-VenafiSession
At C:\Program Files\WindowsPowerShell\Modules\VenafiPS\3.0.2\Classes\VenafiSession.ps1:38 char:21
+ ...             throw "You must first connect to the TPP server with New- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You must first ...w-VenafiSession:String) [], RuntimeException
    + FullyQualifiedErrorId : You must first connect to the TPP server with New-VenafiSession

**Comment by gdbarron** [comment]
Thanks Chris.  Update rolling out now, will be in v3.0.3.
