### ISSUE TITLE
return all values from Get-TppAttribute, including default policy

### ISSUE THREAD

**Issue by Curtmcgirt** [gdbarron/VenafiPS#2]
# Environment

```
Operating System:
VenafiTppPS version:
PowerShell version:
```

# Steps to reproduce

i have found that if i do get-tppattribute on a known-good, IIS-binding-updating, app created in the GUI with the IIS binding port set to 443, there is no "binding port" in the results of get-tppattribute. there is only the "port", which is the winRM port 5985/6. 

# Expected behavior

# Actual behavior

# Screenshots

**Comment by gdbarron** [comment]
@Curtmcgirt this was added in 3.4.0.
