### ISSUE TITLE
Weird message with Import-Module

### ISSUE THREAD

**Issue by wilddev65** [gdbarron/VenafiPS#3]
# Environment

```
Operating System: Win 10
VenafiTppPS version: 2.0.1
PowerShell version: 5.1
```

# Steps to reproduce

Load a new PS shell
Attempt to run script which:
1* Checks to make sure VenafiTppPS in installed and if not installs it from PS Gallery
2* Does an Import-Module VenafiTppPS
3* Does a Get-Module VenafiTppPS
4* Makes a connection to TPP and establishes a New-TppSession

# Expected behavior

Module loads with no errors

# Actual behavior

New-Object : Cannot find type [TppSession]: verify that the assembly containing this type is loaded.
At line:32 char:16
+         return & $origNewObject @psBoundParameters
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

# Screenshots

![image](https://user-images.githubusercontent.com/26489783/92185121-3ab43f00-ee10-11ea-8c2f-9850b4ff03c8.png)

**Comment by gdbarron** [comment]
As per @wilddev65, this is isolated to 1 machine and can be closed.
