### ISSUE TITLE
New-TppCertificate customfield value

### ISSUE THREAD

**Issue by fearnie85** [gdbarron/VenafiPS#31]
For our certificates, we are using 3 custom fields. 

It would be great to have such an option to set custom fields in some hash table when creating certificates. 

For example, the jiraps module has such a feature.

Or perhaps this already has it and I just can't find it. 

Thanks.

**Comment by gdbarron** [comment]
Hi @fearnie85.  You should be able to use `New-TppCertificate -PassThru | Set-TppAttribute -Attribute $myHash`.

**Comment by fearnie85** [comment]
Oh that is perfect!!! Thanks a lot!

**Comment by fearnie85** [comment]
Resolved.
