### ISSUE TITLE
Import-Tppcertificate prompting for Private Key...

### ISSUE THREAD

**Issue by fearnie85** [gdbarron/VenafiPS#37]
Hi All,

I am trying to import a p12 file. 
$POlPathEPO = "\VED\Policy\Certificates\Folder1234\"
$p12cert_path = C:\Cert\MQ\somecert.p12

Import-TppCertificate -PolicyPath $POlPathEPO -CertificatePath $p12cert_path -Password $password2 -VenafiSession $sesh

However, it is constantly prompting for a PrivateKey... I don't understand as p12 includes this. I also changed name to pfx and same issue...

I manually exported the privatekey and the same issue continues.

Am I doing something wrong?
The p12 is a certificate chain. Cert, Intermediate & root...
I tested with just the cert and the same issue continues.

Please let me know what I am doing wrong. thanks!

**Comment by gdbarron** [comment]
It's not you, there's a small issue with the parameter sets. Will fix shortly.

**Comment by fearnie85** [comment]
Perfect thanks a lot! And great work on this module! We've totally utilized it.
