### ISSUE TITLE
Invoke-VenafiRestMethod Lacks Details and Examples

### ISSUE THREAD

**Issue by astro2000j** [gdbarron/VenafiPS#48]
The [Invoke-VenafiRestMethod documentation](https://venafips.readthedocs.io/en/latest/functions/Invoke-VenafiRestMethod/) does not have adequate details for parameters or examples.

**Comment by gdbarron** [comment]
Hi @astro2000j.  This is partially by design as this function, which was once private, is only public as a stopgap for functions that don't exist yet.  I can see adding some examples, but the parameters that are documented should be the only ones you need.  What did you have in mind?
